### ISSUE TITLE
after installed the extention, launch error

### ISSUE THREAD

**Issue by jasoncow007** [yownas/sd-webui-lua#3]
*** Error loading script: sd-webui-lua.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4\extensions\sd-webui-lua\scripts\sd-webui-lua.py", line 16, in <module>
        from modules.shared import opts, cmd_opts, state, log
    ImportError: cannot import name 'log' from 'modules.shared' (D:\sd-webui-aki-v4\modules\shared.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by yownas** [comment]
Thank you for bringing this to my attention. I am mostly using SD.Next and didn't notice that automatic1111 didn't have "log".

But I made an update that should fix it.
